FROM ubuntu:20.04

ENV TZ="Europe/Paris"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone    

RUN apt-get update \
	&& apt-get install -y git \
	&& apt-get install -y opam \
	&& apt-get install -y make wget m4 unzip librsvg2-bin curl bubblewrap \
	&& apt-get install -y pkg-config openssl libssl-dev \
	&& apt-get install -y libpcre3-dev sqlite3 zlib1g-dev \
	&& apt-get install -y libgmp3-dev libsqlite3-dev \
	&& apt-get install -y libcairo-dev \
	&& apt-get install -y graphviz

RUN apt-get clean && apt-get autoremove

# default uid/group, change with --build-arg UID=<newvalue>
ARG UID=1000
ARG GID=1000

# create "local" user
RUN groupadd -g ${GID} grew
RUN useradd -u ${UID} -g ${GID} -m -s /bin/bash grewmatch
USER grewmatch
RUN id
RUN ls -la /home/grewmatch
WORKDIR /home/grewmatch

# install opam related tools/packages
RUN opam init --disable-sandboxing
RUN opam switch create 4.14.0 4.14.0

# TODO does not work like this, the output of opam env must be written to ENV
# RUN eval $(opam env)
RUN opam remote add grew "http://opam.grew.fr"
RUN eval $(opam env) && opam install --yes libcaml-dep2pict grew
RUN eval $(opam env) && opam install --yes fileutils ocsipersist-sqlite eliom


RUN git clone https://gitlab.inria.fr/grew/grew_match_back.git
RUN git clone https://gitlab.inria.fr/grew/grew_match.git

RUN sed -i 's/PERSISTENT_DATA_BACKEND = dbm/PERSISTENT_DATA_BACKEND = sqlite/' \
	/home/grewmatch/grew_match_back/Makefile.options

RUN cat /home/grewmatch/grew_match_back/gmb.conf.in__TEMPLATE \
	| sed 's:<log>__LOG__:<log>/log:' \
	| sed 's:<extern>__EXTERN__:<extern>/home/grewmatch/grew_match_back/static:' \
	| sed 's:<corpora>__CORPORA__:<corpora>/home/grewmatch/grew_match_back/corpora:' \
	| sed 's:<config>__CONFIG__:<config>/home/grewmatch/grew_match/corpora/config.json:' \
	> /home/grewmatch/grew_match_back/gmb.conf.in

# needed to put (head/dependent) tables, compiled out of treebanks at runtime
RUN mkdir /home/grewmatch/grew_match/meta
RUN mkdir /home/grewmatch/grew_match_back/corpora
# needed for save button
RUN mkdir -p /home/grewmatch/grew_match_back/static/shorten

VOLUME [ "/log", "/data" ]

COPY config/config.json /home/grewmatch/grew_match/corpora/config.json
COPY config/lang.json /home/grewmatch/grew_match_back/corpora/lang.json

### EXPERIMENTAL

RUN git clone https://github.com/francescomambrini/Daphne /opt/tmp
RUN mkdir -p /data/daphne && \
    find /opt/tmp/Daphne -type f -name "*.conllu" -exec cp {} /data/daphne \; && \
    rm -R /opt/tmp/

EXPOSE 8000
COPY --chown=grewmatch:grew startscript.sh .


# RUN wget https://gitlab.inria.fr/grew/grew_match_config/-/archive/master/grew_match_config-master.tar.gz
# RUN tar -zxf grew_match_config-master.tar.gz
# RUN mv grew_match_config-master/universal/UD /home/grewmatch/grew_match/corpora/UD
# RUN mv grew_match_config-master/universal/SUD /home/grewmatch/grew_match/corpora/SUD
# RUN mv grew_match_config-master/universal/snippets* /home/grewmatch/grew_match/corpora/
# RUN mv grew_match_config-master/semantics/amr /home/grewmatch/grew_match/corpora/amr


RUN chmod 755 startscript.sh

ENV PATH=${PATH}:/home/grewmatch/.opam/4.14.0/bin
RUN echo $PATH

CMD ["/home/grewmatch/startscript.sh"]


# Use a base image that includes Git and other necessary tools
# FROM grewmatch:latest

# # Install Git and any other dependencies
# RUN apt-get update && \
#     apt-get install -y git

# # Clone the GitHub repository into a directory inside the container
# RUN git clone https://github.com/francescomambrini/Daphne /opt/tmp

# RUN find /opt/tmp/Daphne -type f -name "*.conllu" -exec cp {} /data/daphne \; && \
#     rm -R

# WORKDIR /daphne
